name: Build Plugin

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Find pom.xml
        id: find-pom
        run: |
          POM=$(find . -name "pom.xml" -type f | head -n 1)

          if [ -z "$POM" ]; then
            echo "❌ Nie znaleziono pom.xml!"
            exit 1
          fi

          echo "✅ Znaleziono pom.xml: $POM"
          echo "pom=$POM" >> "$GITHUB_OUTPUT"

      - name: Build with Maven
        run: mvn -B -f "${{ steps.find-pom.outputs.pom }}" clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: RaceWorldProtection
          path: "**/target/*.jar"
